version: "3.7"

services:
  rails-app:
    build: .
    container_name: rails-container
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - gems:/bundles
    ports: 
      - "3333:3333"
    depends_on: 
      - postgres
    stdin_open: true
    tty: true
    networks:
      - app-network
    command: >
      bash -c "./docker/entrypoint.sh"
  
  postgres:
    container_name: postgres-container
    image: library/postgres:9.6-alpine
    ports: 
      - "5431:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root@123
    restart: always
    networks: 
      - app-network

  adminer:
    container_name: adminer-container
    image: adminer
    ports:
      - 8080:8080
    restart: always
    networks: 
      - app-network

volumes:
  gems:
  postgres:

networks:
  app-network:
    driver: "bridge"
