#!/bin/bash
set -e

# This script verify docker and builds the Docker container

if [[ "$OSTYPE" == "darwin"* ]]; then

  if hash docker 2>/dev/null; then
    CONTAINER_RUNTIME=docker
  else
    
    printf "Error! We could not find docker on your Mac! 🆘\n"
    printf "Please install Docker for Mac: 🐳\n"
    printf "https://docs.docker.com/docker-for-mac/install/"

    exit 1

  fi

  if hash docker-compose 2>/dev/null; then
    CONTAINER_COMPOSE=docker-compose
  else

    printf "Error! We could not find a docker-compose on your Mac! 🆘\n"
    printf "Please install Docker for Mac: 🐳\n"
    printf "https://docs.docker.com/docker-for-mac/install/"

    exit 1

  fi

elif [[ "$OSTYPE" == "linux-gnu"* ]]; then

  if hash docker 2>/dev/null; then
    CONTAINER_RUNTIME=docker
  else
    
    printf "Error! We could not find docker on your Linux! 🆘\n"
    printf "Please install Docker for Linux: 🐳\n"
    printf "https://docs.docker.com/engine/install/ubuntu/"

    exit 1

  fi

  if hash docker-compose 2>/dev/null; then
    CONTAINER_COMPOSE=docker-compose
  else

    printf "Error! We could not find a docker-compose on your Mac! 🆘\n"
    printf "Please install Docker for Linux: 🐳\n"
    printf "https://docs.docker.com/compose/install/"

    exit 1

  fi

else

  printf "Oof! Sorry! This OS is unsupported! :( 🆘"

fi

if [ "${CONTAINER_RUNTIME}" = "docker" ]; then

  printf "Depending on your hardware specs, the initial setup can take 😎\n"
  printf "10 to 20 minutes. Please stand by... ⌛\n"

  sleep 10
  
  DATE=`date +%Y%m%d-%H%M%S-%3N`
  docker/build-log 2>&1 | tee log/build-$DATE.log
  
fi
