#!/bin/bash

echo '-----------------------------------------------------'
echo 'BEGIN: docker-compose run rails-app bundle exec rspec'
echo '-----------------------------------------------------'
docker-compose run rails-app bundle exec rspec
echo '---------------------------------------------------'
echo 'END: docker-compose run rails-app bundle exec rspec'
echo '---------------------------------------------------'

echo '--------------------------'
echo 'BEGIN: docker-compose down'
echo '--------------------------'
docker-compose down
echo '------------------------'
echo 'END: docker-compose down'
echo '------------------------'
