default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DATABASE_DEV'] || 'puppies_app_dev' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST'] || 'puppies_app_test' %>

production:
  <<: *default
  database: dev_jobs_prod
