default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: postgres
  username: root
  password: root@123
  port: 5432

development:
  <<: *default
  database: dev_jobs_dev

test:
  <<: *default
  database: dev_jobs_test

production:
  <<: *default
  database: dev_jobs_prod
