#!/bin/bash

# Exit if any command fails
set -e

YELLOW='\033[0;33m'
RED='\033[0;31m'
NO_COLOR='\033[0m'

RUBY_VERSION=$(cat .ruby-version)
NODE_VERSION=$(cat .node-version)

# Check ruby version
if ! ruby --version | grep $RUBY_VERSION > /dev/null; then
  printf "${RED}DevJobs requires ruby ${RUBY_VERSION}${NO_COLOR}. Have a look at: https://github.com/rbenv/rbenv\n"
  exit 1
fi

# Check node version
if ! node --version | grep $NODE_VERSION > /dev/null; then
  printf "${RED}DevJobs requires node ${NODE_VERSION}${NO_COLOR}. Have a look at: https://github.com/nodenv/nodenv\n"
  exit 1
fi

# Install all dependencies
bundle check || bundle install
npm install

# Set up configurable environment variables
if [ ! -f ".env" ]; then
  cp .env.example .env
fi

# Set up the database for both development and test
printf '\n\n' | bundle exec rails db:create db:migrate
printf '\n'

printf "${YELLOW}WELCOME TO DEVJOBS!\n"
printf '\n'
